### ISSUE TITLE
SMTP Unable To Connect

### ISSUE THREAD

**Issue by vivekrjxd** [4nuxd/email-spoofer#1]
An error occurred: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

**Comment by 4nuxd** [comment]
The error [WinError 10060] indicates a connection timeout. Here's a quick checklist:

Verify Server Address: Ensure the hostname or IP is correct
Check Port: Confirm the target port is open using

Then Try Again

**Comment by vivekrjxd** [comment]
Ok Thanks
